package org.incha.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import org.graphstream.graph.Graph;
import org.incha.core.jswingripples.GraphBuilder;

public class Theme_changer implements ActionListener {
	
	int theme;
	public Theme_changer(int i){
		theme = i;
	}

	@Override
	public void actionPerformed(ActionEvent e) {
		Graph g1 = GraphBuilder.getInstance().getDependencyGraph();
		Graph g2 = GraphBuilder.getInstance().getImpactSetGraph();
		String style = "";
		g1.removeAttribute("ui.stylesheet");
		g2.removeAttribute("ui.stylesheet");
		if (theme == 0){
			style = "graph{fill-color:#fff4e6; } node {size-mode:dyn-size; size: 40px, 40px;shape: circle;fill-color: #854442;text-alignment: at-right;text-size:20;text-color: #3c2f2f;stroke-mode:plain; stroke-color:#3c2f2f; stroke-width:2;} edge{fill-color:#3c2f2f; shape:cubic-curve;size:3;} node:clicked { fill-color: darkmagenta;} node:selected{stroke-mode:plain; stroke-color:black; stroke-width:5;} node.blank {size-mode:dyn-size; size: 40px, 40px;shape: circle;fill-color: black;text-alignment: at-right;text-size:20;text-color: #3c2f2f;stroke-mode:plain; stroke-color:#3c2f2f; stroke-width:2;} node.changed {size-mode:dyn-size; size: 40px, 40px;shape: circle;fill-color: red;text-alignment: at-right;text-size:20;text-color: #3c2f2f;stroke-mode:plain; stroke-color:#3c2f2f; stroke-width:2;} node.impacted {size-mode:dyn-size; size: 40px, 40px;shape: circle;fill-color: darkred;text-alignment: at-right;text-size:20;text-color: #3c2f2f;stroke-mode:plain; stroke-color:#3c2f2f; stroke-width:2;} node.next {size-mode:dyn-size; size: 40px, 40px;shape: circle;fill-color: green;text-alignment: at-right;text-size:20;text-color: #3c2f2f;stroke-mode:plain; stroke-color:#3c2f2f; stroke-width:2;} node.propagating {size-mode:dyn-size; size: 40px, 40px;shape: circle;fill-color: #FF8C00;text-alignment: at-right;text-size:20;text-color: #3c2f2f;stroke-mode:plain; stroke-color:#3c2f2f; stroke-width:2;}";
		}else if(theme == 1){
			style = "graph { canvas-color: black; fill-mode: gradient-vertical; fill-color: black, #004; padding: 20px; } node { text-visibility-mode: under-zoom; text-visibility: 0.3;text-size: 18; text-color: white;shape: circle; size-mode: dyn-size; size: 10px; fill-mode: gradient-radial; fill-color: #FFFC, #FFF0; stroke-mode: none; shadow-mode: gradient-radial; shadow-color: #FFF5, #FFF0; shadow-width: 5px; shadow-offset: 0px, 0px; } node:clicked { fill-color: #F00A, #F000; } node:selected { fill-color: #00FA, #00F0; } edge { shape: L-square-line; size: 1px; fill-color: #FFF3; fill-mode: plain; arrow-shape: none; } sprite { shape: circle; fill-mode: gradient-radial; fill-color: #FFF8, #FFF0; } node.blank { text-visibility-mode: under-zoom; text-visibility: 0.3;text-size: 18; text-color: white;shape: circle; size-mode: dyn-size; size: 10px; fill-mode: gradient-radial; fill-color: black, #004; stroke-mode: none; shadow-mode: gradient-radial; shadow-color: #FFF5, #FFF0; shadow-width: 5px; shadow-offset: 0px, 0px; } node.changed { text-visibility-mode: under-zoom; text-visibility: 0.3;text-size: 18; text-color: white;shape: circle; size-mode: dyn-size; size: 10px; fill-mode: gradient-radial; fill-color: red, #FFF0; stroke-mode: none; shadow-mode: gradient-radial; shadow-color: #FFF5, #FFF0; shadow-width: 5px; shadow-offset: 0px, 0px; } node.impacted { text-visibility-mode: under-zoom; text-visibility: 0.3;text-size: 18; text-color: white;shape: circle; size-mode: dyn-size; size: 10px; fill-mode: gradient-radial; fill-color: darkred, #FFF0; stroke-mode: none; shadow-mode: gradient-radial; shadow-color: #FFF5, #FFF0; shadow-width: 5px; shadow-offset: 0px, 0px; } node.next { text-visibility-mode: under-zoom; text-visibility: 0.3;text-size: 18; text-color: white;shape: circle; size-mode: dyn-size; size: 10px; fill-mode: gradient-radial; fill-color: green, #FFF0; stroke-mode: none; shadow-mode: gradient-radial; shadow-color: #FFF5, #FFF0; shadow-width: 5px; shadow-offset: 0px, 0px; } node.propagating { text-visibility-mode: under-zoom; text-visibility: 0.3;text-size: 18; text-color: white;shape: circle; size-mode: dyn-size; size: 10px; fill-mode: gradient-radial; fill-color: #FF8C00, #FFF0; stroke-mode: none; shadow-mode: gradient-radial; shadow-color: #FFF5, #FFF0; shadow-width: 5px; shadow-offset: 0px, 0px; }";
		}else if(theme == 2){
			style = "graph {fill-color: #f5f5f5;} node { text-size: 18; fill-color: #7ddc1f; text-color: #444444; shape: circle; text-alignment: at-right; stroke-mode:plain; stroke-color:#0073e5; stroke-width:3; size-mode:dyn-size;} edge{fill-color:#0073e5; shape:blob;size: 3;}     node.blank { text-size: 18; fill-color: black; text-color: #444444; shape: circle; text-alignment: at-right; stroke-mode:plain; stroke-color:#0073e5; stroke-width:3; size-mode:dyn-size;}      node.changed { text-size: 18; fill-color: red; text-color: #444444; shape: circle; text-alignment: at-right; stroke-mode:plain; stroke-color:#0073e5; stroke-width:3; size-mode:dyn-size;}      node.impacted { text-size: 18; fill-color: darkred; text-color: #444444; shape: circle; text-alignment: at-right; stroke-mode:plain; stroke-color:#0073e5; stroke-width:3; size-mode:dyn-size;}       node.next { text-size: 18; fill-color: green; text-color: #444444; shape: circle; text-alignment: at-right; stroke-mode:plain; stroke-color:#0073e5; stroke-width:3; size-mode:dyn-size;}        node.propagating { text-size: 18; fill-color: #FF8C00; text-color: #444444; shape: circle; text-alignment: at-right; stroke-mode:plain; stroke-color:#0073e5; stroke-width:3; size-mode:dyn-size;}";
		}else if(theme == 3){
			style = "graph {fill-color: #1C232B, #2D3645; fill-mode: gradient-vertical;} edge{arrow-shape:circle;fill-color:#626A77;shape:line;} node { size-mode:dyn-size; text-size: 18; fill-color: rgba(0,0,0,0); text-color: #626A77; shape: circle; text-alignment: at-right; stroke-mode:plain; stroke-color:#626A77; stroke-width:3;} edge{fill-color:#626A77; shape:blob;size: 3;} node.blank { size-mode:dyn-size; text-size: 18; fill-color: rgba(0,0,0,0); text-color: #626A77; shape: circle; text-alignment: at-right; stroke-mode:plain; stroke-color:black; stroke-width:3;} node.changed { size-mode:dyn-size; text-size: 18; fill-color: rgba(0,0,0,0); text-color: #626A77; shape: circle; text-alignment: at-right; stroke-mode:plain; stroke-color:red; stroke-width:3;} node.impacted { size-mode:dyn-size; text-size: 18; fill-color: rgba(0,0,0,0); text-color: #626A77; shape: circle; text-alignment: at-right; stroke-mode:plain; stroke-color:darkred; stroke-width:3;} node.next { size-mode:dyn-size; text-size: 18; fill-color: rgba(0,0,0,0); text-color: #626A77; shape: circle; text-alignment: at-right; stroke-mode:plain; stroke-color:green; stroke-width:3;} node.propagating { size-mode:dyn-size; text-size: 18; fill-color: rgba(0,0,0,0); text-color: #626A77; shape: circle; text-alignment: at-right; stroke-mode:plain; stroke-color:#FF8C00; stroke-width:3;}";
		}else if(theme == 4){
			style = "graph { fill-color: black; } edge{fill-color:#626A77;shape:angle;size:15;}        node {text-color: white;text-visibility-mode: under-zoom; text-visibility: 0.3; size-mode:dyn-size; size: 15px; fill-color: #44F; stroke-mode: plain; stroke-width: 2px; stroke-color: #CCF; shadow-mode: gradient-radial; shadow-width: 10px; shadow-color: #EEF, #000; shadow-offset: 0px; } edge { fill-color: #CCF; size: 2px; }      node.blank {text-color: white;text-visibility-mode: under-zoom; text-visibility: 0.3; size-mode:dyn-size; size: 15px; fill-color: black; stroke-mode: plain; stroke-width: 2px; stroke-color: #CCF; shadow-mode: gradient-radial; shadow-width: 10px; shadow-color: #EEF, #000; shadow-offset: 0px; }       node.changed {text-color: white;text-visibility-mode: under-zoom; text-visibility: 0.3; size-mode:dyn-size; size: 15px; fill-color: red; stroke-mode: plain; stroke-width: 2px; stroke-color: #CCF; shadow-mode: gradient-radial; shadow-width: 10px; shadow-color: #EEF, #000; shadow-offset: 0px; }         node.impacted {text-color: white;text-visibility-mode: under-zoom; text-visibility: 0.3; size-mode:dyn-size; size: 15px; fill-color: darkred; stroke-mode: plain; stroke-width: 2px; stroke-color: #CCF; shadow-mode: gradient-radial; shadow-width: 10px; shadow-color: #EEF, #000; shadow-offset: 0px; }         node.next {text-color: white;text-visibility-mode: under-zoom; text-visibility: 0.3; size-mode:dyn-size; size: 15px; fill-color: green; stroke-mode: plain; stroke-width: 2px; stroke-color: #CCF; shadow-mode: gradient-radial; shadow-width: 10px; shadow-color: #EEF, #000; shadow-offset: 0px; }        node.propagating {text-color: white;text-visibility-mode: under-zoom; text-visibility: 0.3; size-mode:dyn-size; size: 15px; fill-color: #FF8C00; stroke-mode: plain; stroke-width: 2px; stroke-color: #CCF; shadow-mode: gradient-radial; shadow-width: 10px; shadow-color: #EEF, #000; shadow-offset: 0px; }";
		}else if(theme == 5){
			style = "graph {fill-color: #e1e1e1;} node { text-visibility-mode: under-zoom; text-visibility: 0.3; size-mode:dyn-size; size: 20px; fill-color: #4a6084, rgba(0,0,0,0); fill-mode: gradient-radial; stroke-mode:plain; stroke-color:#9ca2c4; stroke-width:3; text-size: 15; text-color: #292929;} edge{fill-color:#9ca2c4;shape:line;size:10;} node.blank {text-visibility-mode: under-zoom; text-visibility: 0.3; size-mode:dyn-size; size: 20px; fill-color: black, rgba(0,0,0,0); fill-mode: gradient-radial; stroke-mode:plain; stroke-color:#9ca2c4; stroke-width:3; text-size: 15; text-color: #292929;} node.changed { text-visibility-mode: under-zoom; text-visibility: 0.3; size-mode:dyn-size; size: 20px; fill-color: red, rgba(0,0,0,0); fill-mode: gradient-radial; stroke-mode:plain; stroke-color:#9ca2c4; stroke-width:3; text-size: 15; text-color: #292929;} node.impacted { text-visibility-mode: under-zoom; text-visibility: 0.3; size-mode:dyn-size; size: 20px; fill-color: darkred, rgba(0,0,0,0); fill-mode: gradient-radial; stroke-mode:plain; stroke-color:#9ca2c4; stroke-width:3; text-size: 15; text-color: #292929;} node.next { text-visibility-mode: under-zoom; text-visibility: 0.3; size-mode:dyn-size; size: 20px; fill-color: green, rgba(0,0,0,0); fill-mode: gradient-radial; stroke-mode:plain; stroke-color:#9ca2c4; stroke-width:3; text-size: 15; text-color: #292929;} node.propagating { text-visibility-mode: under-zoom; text-visibility: 0.3; size-mode:dyn-size; size: 20px; fill-color: #FF8C00, rgba(0,0,0,0); fill-mode: gradient-radial; stroke-mode:plain; stroke-color:#9ca2c4; stroke-width:3; text-size: 15; text-color: #292929;}";
		}
		g1.addAttribute("ui.stylesheet", style);
		g2.addAttribute("ui.stylesheet", style);

	}

}
